# Generated by Django 5.1.4 on 2025-02-17 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='astronaut',
            name='agency',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='astronauts', to='core.agency'),
            preserve_default=False,
        ),
    ]
