# Generated by Django 5.1.4 on 2025-02-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_astronaut_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacecraft',
            name='visited_planets',
            field=models.ManyToManyField(related_name='spacecrafts', to='core.planet'),
        ),
    ]
